// legacy (still used by LoadingScreenContainer)
export const EDITOR_NOTIFICATION_UPDATE = "EDITOR_NOTIFICATION_UPDATE";
export const EDITOR_NOTIFICATION_RESET = "EDITOR_NOTIFICATION_RESET";

// notification-center actions
export const EDITOR_NOTIFICATIONS_SET = "EDITOR_NOTIFICATIONS_SET";
export const EDITOR_NOTIFICATION_SOCKET_UPDATE = "EDITOR_NOTIFICATION_SOCKET_UPDATE";
export const EDITOR_NOTIFICATION_MARK_READ = "EDITOR_NOTIFICATION_MARK_READ";
