export const EDITOR_LOAD_REQUEST = "EDITOR_LOAD_REQUEST";
export const EDITOR_LOAD_SUCCESS = "EDITOR_LOAD_SUCCESS";
export const EDITOR_LOAD_FAILURE = "EDITOR_LOAD_FAILURE";

export const EDITOR_UPDATE_SEGMENT_REQUEST = "EDITOR_UPDATE_SEGMENT_REQUEST";
export const EDITOR_UPDATE_SEGMENT_SUCCESS = "EDITOR_UPDATE_SEGMENT_SUCCESS";
export const EDITOR_UPDATE_SEGMENT_FAILURE = "EDITOR_UPDATE_SEGMENT_FAILURE";

export const EDITOR_DELETE_SEGMENT_REQUEST = "EDITOR_DELETE_SEGMENT_REQUEST";
export const EDITOR_DELETE_SEGMENT_SUCCESS = "EDITOR_DELETE_SEGMENT_SUCCESS";
export const EDITOR_DELETE_SEGMENT_FAILURE = "EDITOR_DELETE_SEGMENT_FAILURE";

export const EDITOR_APPLY_CHANGES_REQUEST = "EDITOR_APPLY_CHANGES_REQUEST";
export const EDITOR_APPLY_CHANGES_SUCCESS = "EDITOR_APPLY_CHANGES_SUCCESS";
export const EDITOR_APPLY_CHANGES_FAILURE = "EDITOR_APPLY_CHANGES_FAILURE";

export const EDITOR_CHANGE_LANGUAGE_REQUEST = "EDITOR_CHANGE_LANGUAGE_REQUEST";
export const EDITOR_CHANGE_LANGUAGE_SUCCESS = "EDITOR_CHANGE_LANGUAGE_SUCCESS";
export const EDITOR_CHANGE_LANGUAGE_FAILURE = "EDITOR_CHANGE_LANGUAGE_FAILURE";

export const EDITOR_SET_TARGET_LANGUAGE = "EDITOR_SET_TARGET_LANGUAGE";

export const EDITOR_REDUB_REQUEST = "EDITOR_REDUB_REQUEST";
export const EDITOR_REDUB_SUCCESS = "EDITOR_REDUB_SUCCESS";
export const EDITOR_REDUB_FAILURE = "EDITOR_REDUB_FAILURE";
