export const JOBS_FETCH_REQUEST = "JOBS_FETCH_REQUEST";
export const JOBS_FETCH_SUCCESS = "JOBS_FETCH_SUCCESS";
export const JOBS_FETCH_FAILURE = "JOBS_FETCH_FAILURE";

export const JOB_DELETE_REQUEST = "JOB_DELETE_REQUEST";
export const JOB_DELETE_SUCCESS = "JOB_DELETE_SUCCESS";
export const JOB_DELETE_FAILURE = "JOB_DELETE_FAILURE";

export const JOB_NOTIFICATIONS_UPDATE = "JOB_NOTIFICATIONS_UPDATE";
export const JOB_STATUS_BULK_UPDATE = "JOB_STATUS_BULK_UPDATE";